vich_uploader:
    db_driver: orm

    mappings:
       image_question:
           uri_prefix: /images/questions
           upload_destination: '%kernel.project_dir%/public/images/assets/imgs'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
